### ISSUE TITLE
Not able to generate saved reports (On-demand reports) through Reporting-CLI in opensearch dashboards.

### ISSUE THREAD

**Issue by Rajeshdaneti** [opensearch-project/reporting-cli#25]
Hi Rupal,
I am trying to generate a saved report through reporting-cli but getting error. Not sure whether giving a correct url- 

reporting --url https://localhost:5601/app/reports-dashboards#/YNfdEIUBEXSpUhMUQPpL --format pdf --filename sales_by_cat.pdf

reporting --url https://localhost:5601/app/reports-dashboards#/report_definition_details/Kz3u64QBun0oheBCcZQK --format pdf --filename dummy1

reporting --url hhttps://localhost:5601/api/reporting/generateReport/YNfdEIUBEXSpUhMUQPpL  --format pdf --filename sales_by_cat.pdf

Please help me, how to get a correct url of saved report. When I am checking saved report url from user interface - got below link, which shows report details only -
https://localhost:5601/app/reports-dashboards#/report_definition_details/YNfdEIUBEXSpUhMUQPpL

I tried many ways but not able to generate. I suspect link is not correct. Please give some samples for generating on-demand saved reports through report-cli.

Regards
Rajesh Kumar.

**Comment by rupal-bq** [comment]
Hi Rajesh,

We recently released reporting-cli. Please check https://opensearch.org/docs/latest/dashboards/reporting-cli/rep-cli-index/ for more information.
