### ISSUE TITLE
[FEATURE] Add opensearch-reporting-cli-1.0.0.tgz to the release page

### ISSUE THREAD

**Issue by 51CGO** [opensearch-project/reporting-cli#30]
(I didn't know where to put this request. I'm not sure it's a feature reuqest)

The installation instructions indicate :
"npm install -g opensearch-reporting-cli-1.0.0.tgz"

But opensearch-reporting-cli-1.0.0.tgz is not available neither on opensearch.org, nor on the page of the release 1.0.0 on github.
Can you provide this artifact ?

Thank you.

**Comment by rupal-bq** [comment]
Hi @51CGO,
Currently you can click on Artifacts link given in [doc](https://opensearch.org/docs/latest/dashboards/reporting-cli/rep-cli-install/#downloading-and-installing-the-reporting-cli-from-opensearchorg)
Or https://artifacts.opensearch.org/reporting-cli/opensearch-reporting-cli-1.0.0.tgz
