### ISSUE TITLE
[BUG] OpenSearch Reporting CLI Lambda not evaluating certain environment variables

### ISSUE THREAD

**Issue by aaronbrighton** [opensearch-project/reporting-cli#38]
### What is the bug?
_When using the OpenSearch Reporting CLI Lambda function, the following environment variables are not evaluated correctly.  Instead they are using the default values._

- _OPENSEARCH_EMAIL_SUBJECT_
- _OPENSEARCH_EMAIL_NOTE_

### How can one reproduce the bug?
_Follow the instructions here (https://opensearch.org/docs/latest/dashboards/reporting-cli/rep-cli-lambda/) and set any of the above environment variables on the Lambda function instead of passing them as the event object._

### What is the expected behavior?
_Expectation is that the email sent by the Lambda function would contain a non-default subject and note._

### What is your host/environment?
_N/A_

### Do you have any screenshots?
_See description for observed behavior._

### Do you have any additional context?
_It appears the following code function causes bypass of the environment variables: https://github.com/opensearch-project/reporting-cli/blob/af8d3073ec5488d487410f6e70a626f970399f05/src/arguments.js#L78_

**Comment by rupal-bq** [comment]
Hi @aaronbrighton, this will be fixed in next release v1.1.0. 

If you would like to try/test before the release, you can refer to doc for building docker image from source code https://github.com/opensearch-project/reporting-cli/blob/main/docs/examples/lambda_container_image_from_source.md.
