### ISSUE TITLE
[BUG] OpenSearch Reporting CLI Lambda always prepends "tmp" to email attachments

### ISSUE THREAD

**Issue by aaronbrighton** [opensearch-project/reporting-cli#43]
### What is the bug?
_When using the OpenSearch Reporting CLI Lambda function, the filename for email attachments always has "tmp" prepended to the filename._

### How can one reproduce the bug?
_Follow the instructions here (https://opensearch.org/docs/latest/dashboards/reporting-cli/rep-cli-lambda/)._

### What is the expected behavior?
_Attachment filename should look something like this: `opensearch-report-2023-03-31T12-00-51.433Z` instead of `tmpopensearch-report-2023-03-31T12-00-51.433Z`._

### What is your host/environment?
_N/A_

### Do you have any screenshots?
_See description for observed behavior._

### Do you have any additional context?
_It appears the following code which defines where to temporarily save the file is being propagated to the email function that attaches the file to the email and incorporating the folder name "tmp" in the value:_

https://github.com/opensearch-project/reporting-cli/blob/6feb950bff484e6c6ee3b75552c50c12c4a3f1a8/src/run.js#L13

https://github.com/opensearch-project/reporting-cli/blob/6feb950bff484e6c6ee3b75552c50c12c4a3f1a8/src/email-helpers.js#L111

Potentially easy fix by wrapping the value on line 111 above with path.basename()?

**Comment by joshuali925** [comment]
i feel this was a workaround for current directory not writable but user can write to `/tmp` dir? @rupal-bq

**Comment by rupal-bq** [comment]
> i feel this was a workaround for current directory not writable but user can write to `/tmp` dir? @rupal-bq

Yes. In Lambda we can write only to the `/tmp`.

https://repost.aws/questions/QUoCCNNS59RryAKeEBezXFcg/how-to-work-around-directory-permissions-in-aws-lambda
