### ISSUE TITLE
Request to remove @zhongnansu from maintainer/code owner list

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/reporting-cli#45]
https://github.com/opensearch-project/reporting-cli/blob/main/MAINTAINERS.md#current-maintainers
Hi team, please remove me from the maintainer and code owner list of this repo. I believe it's a mistake, since I never contribute anything to this repo. 

Thanks

cc: @rupal-bq @joshuali925 @derek-ho

**Comment by joshuali925** [comment]
closed by https://github.com/opensearch-project/reporting-cli/pull/46
